### ISSUE TITLE
java.io.IOException: cosn://null : java.lang.IllegalArgumentException: uin and request id must be exist

### ISSUE THREAD

**Issue by chufucun** [tencentyun/hadoop-cos#36]
when `fs.cosn.credentials.provider` is not specified, the following error.  
```
java.io.IOException: cosn://null : java.lang.IllegalArgumentException: uin and request id must be exist

	at org.apache.hadoop.fs.CosNativeFileSystemStore.handleException(CosNativeFileSystemStore.java:1060)
	at org.apache.hadoop.fs.CosNativeFileSystemStore.initialize(CosNativeFileSystemStore.java:209)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
	at com.sun.proxy.$Proxy7.initialize(Unknown Source)
	at org.apache.hadoop.fs.CosFileSystem.initialize(CosFileSystem.java:104)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3354)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:124)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3403)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3371)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:477)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:226)
	at org.apache.hadoop.fs.CosFileSystemTest.getFileStatus(CosFileSystemTest.java:15)
```

Test:

```java
  @Test
  public void getFileStatus() throws IOException {
    FileSystem fs = CosFileSystem.get(new Configuration());
    String pathname = "/test-warehouse/tinytable";
    Path path = new Path(pathname);
    System.out.println(fs.getFileStatus(path));
  }
```
New authentication: DLFInstanceCredentialsProvider initialization error,  there should not be thrown exception.
https://github.com/tencentyun/hadoop-cos/blob/master/src/main/java/org/apache/hadoop/fs/auth/DLFInstanceCredentialsProvider.java#L41

**Comment by yuyang733** [comment]
你好，非常抱歉。这个最近的一个PR修复了。
