### ISSUE TITLE
apache hadoop-3.3.0 return  java.lang.NoClassDefFoundError: org/apache/hadoop/fs/chdfs/PosixSeekable

### ISSUE THREAD

**Issue by lifehacking** [tencentyun/hadoop-cos#98]
apache hadoop-3.3.0 with hadoop-cos v8.2.1

1 core-site.xml（when i use tencents cos config）
<property>
     <name>fs.cosn.impl</name>
     <value>org.apache.hadoop.fs.CosFileSystem</value>
</property>
<property>
     <name>fs.AbstractFileSystem.cosn.impl</name>
     <value>org.apache.hadoop.fs.CosN</value>
</property>

hadoop fs -ls -R cosn://xxx/  return

2023-01-13 06:38:43,527 INFO fs.RangerCredentialsClient: begin to init ranger client, impl []
2023-01-13 06:38:43,691 INFO fs.CosNativeFileSystemStore: hadoop cos retry times: 200, cos client retry times: 5
2023-01-13 06:38:44,669 INFO fs.CosFileSystem: The cos bucket is the normal bucket.
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/fs/chdfs/PosixSeekable
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.apache.hadoop.fs.CosFileSystem.getActualFileSystemByClassName(CosFileSystem.java:160)
        at org.apache.hadoop.fs.CosFileSystem.initialize(CosFileSystem.java:144)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3414)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:158)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3474)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3442)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:524)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
        at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:352)
        at org.apache.hadoop.fs.shell.Command.expandArgument(Command.java:250)
        at org.apache.hadoop.fs.shell.Command.expandArguments(Command.java:233)
        at org.apache.hadoop.fs.shell.FsCommand.processRawArguments(FsCommand.java:104)
        at org.apache.hadoop.fs.shell.Command.run(Command.java:177)
        at org.apache.hadoop.fs.FsShell.run(FsShell.java:327)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:90)
        at org.apache.hadoop.fs.FsShell.main(FsShell.java:390)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.chdfs.PosixSeekable
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 31 more

2 core-site.xml （apache hadoop config from tencent cloud website）
<property>
     <name>fs.cosn.impl</name>
     <value>org.apache.hadoop.fs.cosn.CosNFileSystem</value>
</property>
<property>
     <name>fs.AbstractFileSystem.cosn.impl</name>
     <value>org.apache.hadoop.fs.cosn.CosN</value>
</property>

hadoop fs -ls -R cosn://xxx/  return

java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.cosn.CosNFileSystem not found
        at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2665)
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3378)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3411)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:158)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3474)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3442)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:524)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
        at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:352)
        at org.apache.hadoop.fs.shell.Command.expandArgument(Command.java:250)
        at org.apache.hadoop.fs.shell.Command.expandArguments(Command.java:233)
        at org.apache.hadoop.fs.shell.FsCommand.processRawArguments(FsCommand.java:104)
        at org.apache.hadoop.fs.shell.Command.run(Command.java:177)
        at org.apache.hadoop.fs.FsShell.run(FsShell.java:327)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:90)
        at org.apache.hadoop.fs.FsShell.main(FsShell.java:390)
Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.cosn.CosNFileSystem not found
        at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2569)
        at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2663)
        ... 16 more

3 core-site.xml （apache hadoop website）

    <property>
        <name>fs.cosn.impl</name>
        <value>org.apache.hadoop.fs.cosn.CosNFileSystem</value>
        <description>The implementation class of the CosN Filesystem</description>
    </property>

    <property>
        <name>fs.AbstractFileSystem.cosn.impl</name>
        <value>org.apache.hadoop.fs.cos.CosN</value>
        <description>The implementation class of the CosN AbstractFileSystem.</description>
    </property>

fs.AbstractFileSystem.cosn.impl value is org.apache.hadoop.fs.cos.CosN or org.apache.hadoop.fs.cosn.CosN ？

**Comment by lifehacking** [comment]
ofs-sdk-definition-1.0.4.jar also need put in ./share/hadoop/tools/lib/
 
it's ok

**Comment by yuyang733** [comment]
ofs-sdk-defition-1.0.4.jar need to be added into the classpath with the hadoop-cos.
